FROM node:alpine as builder
WORKDIR /app
COPY package.json /app
RUN npm install --silent
COPY . /app
RUN npm run build --prod --configuration=production
FROM nginx:1.19.7-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder app/dist/frontend /usr/share/nginx/html
